# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    # gradle(task: "clean assembleRelease")
    build()
    crashlytics(
      api_token: "6d68f20a854ffdbb8f7a2e495dc0e8ff55868cff",
      build_secret: "d52dd85e06773bec7a4d0d02f1fe5e9f696572bb64e3eb67f8783f7b72ad6478",
      apk_path: "../build/app/outputs/apk/release/app-release.apk",
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Increment build numer"
  lane :build do
    # Return the number of commits in current git branch
    build_number = number_of_commits()
    Dir.chdir "../.." do
      sh("pwd")
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "apk", "--build-number=#{build_number}")
    end
  end
end
